language: php
php:
  - "5.4"
  - "5.3"
  - "5.2"
before_script:
  - pear install --alldeps pear/PHP_CodeSniffer
  - phpenv rehash
script:
  - phpunit -c ./build.xml
  - phpcs --extensions=php -p --standard=PSR2 ./